name 'puppet-krb5'
version '0.0.2'

author 'IvanBayan'
license 'GPLv3'
project_page 'https://github.com/IvanBayan/puppet-krb5'
source ''
summary ''
description 'Generate krb5.conf'
dependency 'ripienaar/concat', '>=1'
