name 'IvanBayan-krb5'
version '0.0.3'

author 'IvanBayan'
license 'GPLv3'
project_page 'https://github.com/IvanBayan/puppet-krb5'
source 'https://github.com/IvanBayan/puppet-krb5.git'
summary 'Generate krb5.conf'
description 'Generate krb5.conf'
dependency 'puppetlabs/concat', '>=1.0.0'
